# Generated by Django 5.2.6 on 2025-09-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.TextField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.JSONField(default=list)),
                ('advancedPayment', models.FloatField(default=0)),
                ('original_amount', models.FloatField(default=0)),
                ('total_amount_paid', models.FloatField(default=0)),
                ('total_amount_due', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('totalPayableAmount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlotDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotEast', models.TextField(blank=True, default='0', null=True)),
                ('plotWest', models.TextField(blank=True, default='0', null=True)),
                ('plotNorth', models.TextField(blank=True, default='0', null=True)),
                ('plotSouth', models.TextField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField(blank=True, default=dict, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.TextField(blank=True, default='0', null=True)),
                ('plot_area', models.TextField(blank=True, null=True)),
                ('roadDirection', models.CharField(blank=True, max_length=30, null=True)),
                ('roadWidth', models.CharField(blank=True, max_length=10, null=True)),
                ('plot_dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.plotdimensions')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_project_pending', models.BooleanField(default=True)),
                ('is_payment_pending', models.BooleanField(default=True)),
                ('referred_by', models.CharField(blank=True, default='Self', max_length=255, null=True)),
                ('image_link', models.URLField(blank=True, default=None, null=True)),
                ('total_bill', models.IntegerField(blank=True, default=0)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('specialNotes', models.TextField(blank=True, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.address')),
                ('client_requirements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.clientrequirements')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.email')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.name')),
                ('payment_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.paymentdetails')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.phonenumber')),
                ('plot_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.plotdetails')),
                ('services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMS.services')),
            ],
        ),
    ]
