"""
Django settings for InterarchCMS project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
from cryptography.fernet import Fernet
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

KEY = os.getenv("TEMPLATE_KEY")
if not KEY:
    raise SystemExit("Set TEMPLATE_KEY in .env before running Django.")

FERNET = Fernet(KEY.encode())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#8z63ga2-ejs3((p0r$x79n13o@3-=i$tg_sq)j(0_j%1@zqtd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost","127.0.0.1","interarch.share.zrok.io"]

# This key is important ->  iELexOrVelrIn64NsozuXn0gbAiuIJ67jHoXQr0_LD4=

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CMS',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'InterarchCMS.urls'

print("THis is the base_DIR :", BASE_DIR)
def decrypt_template(path):
    """Decrypts .enc templates on the fly"""
    if path.endswith(".enc"):
        with open(path, "rb") as f:
            data = FERNET.decrypt(f.read())
            return data.decode("utf-8")
    else:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "CMS" / "templates"],
        "APP_DIRS": False,  # must be False when using custom loaders
        "OPTIONS": {
            # Use our encrypted loader
            "loaders": [
                ("CMS.templateLoader.EncryptedTemplateLoader", [BASE_DIR / "CMS" / "templates"]),
            ],
            # ✅ Context processors required by admin
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",    # Required for admin nav sidebar
                "django.contrib.auth.context_processors.auth",   # Required for auth features
                "django.contrib.messages.context_processors.messages",  # Required for messages
            ],
        },
    },
]

WSGI_APPLICATION = 'InterarchCMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = [
    
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# URL prefix to access these files
MEDIA_URL = '/uploads/'